<script>
    window.addEventListener('DOMContentLoaded', function() {
        var form = document.querySelector('.contact_form');
        form.addEventListener('submit', function(event) {
            var input = form.querySelector('input[type="email"]');
            function generateError (text) {
                var error = document.createElement('div');
                error.className = 'error';
                error.style.color = 'red';
                error.innerHTML = text;
                return error;
            }
            if (input && input.value) {
                var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
                if (!input.value.match(mailformat)) {
                    event.preventDefault();

                    if (input.closest('.field_container').querySelector('.error')) {
                        input.closest('.field_container').querySelector('.error').remove()
                    }
                    var error = generateError('Format d’e-mail incorrect');
                    input.closest('.field_container').appendChild(error);
                }
            }
        });
    });
</script>

<form data-form-language="de" id="contact_form_1_de"
      class="contact_form contact_form_de validate_type_all contact_form_cols_2"
      action="//web.swissnewsletter.ch/e/13aced75bc14ba2f/form/de/anmeldeformular.html"
      method="post"  novalidate="novalidate">
    <ul class="field_errors"></ul>
    <div class="col_0">

        <h1 id="headline1_1" class="headline1">Inscription ou modification de vos données personnelles</h1>
        <p id="text_2" class="text">Merci pour votre intérêt !</p>
        <p id="text_2" class="text">Afin de recevoir nos nouvelles ou pour tenir notre carnet d'adresses à jour, nous vous prions de remplir ce formulaire.</p>
        <p id="text_2" class="text">Avec nos salutations distinguées, Pascal Gemperli</p>

        <div class="line" id="line_4"></div>
        <div class="field_container contact_field_container"
             id="contact_field_email_container">
            <label for="data_contact_email">Adresse email    <span class="required">*</span></label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_email" name="data[contact][email]" required="required" >
        </div>
        <div class="line" id="line_77"></div>
        <h1 class="headline1" id="headline1_81">Je m'intéresse à vos services et engagements suivants   <span class="required">*</span></h1>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_28_container">
            <input type="checkbox"     id="data_contact_customfield_values_28_content" name="data[contact][customfield_values][28][content]" value="1">
            <label for="data_contact_customfield_values_28_content">Gemperli-Médiation (en entreprise, PCE, B2B, particuliers, divorce)</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_17_container">
            <input type="checkbox"     id="data_contact_customfield_values_17_content" name="data[contact][customfield_values][17][content]" value="1">
            <label for="data_contact_customfield_values_17_content">amiable.ch</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_25_container">
            <input type="checkbox"     id="data_contact_customfield_values_25_content" name="data[contact][customfield_values][25][content]" value="1">
            <label for="data_contact_customfield_values_25_content">Gemperli-Coaching (pour dirigeants et particuliers)</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_26_container">
            <input type="checkbox"     id="data_contact_customfield_values_26_content" name="data[contact][customfield_values][26][content]" value="1">
            <label for="data_contact_customfield_values_26_content">Gemperli-Diversité (intégration, prévention de l'extrémisme)</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_18_container">
            <input type="checkbox"     id="data_contact_customfield_values_18_content" name="data[contact][customfield_values][18][content]" value="1">
            <label for="data_contact_customfield_values_18_content">ae-Centre, Maghreb (coopération, médiation)</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_23_container">
            <input type="checkbox"     id="data_contact_customfield_values_23_content" name="data[contact][customfield_values][23][content]" value="1">
            <label for="data_contact_customfield_values_23_content">Écologie, Les Vert.e.s, Zéro déchet</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="line" id="line_83"></div>
        <h1 class="headline1" id="headline1_90">Je suis</h1>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_30_container">
            <input type="checkbox"     id="data_contact_customfield_values_30_content" name="data[contact][customfield_values][30][content]" value="1">
            <label for="data_contact_customfield_values_30_content">Médiatrice, médiateur</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_22_container">
            <input type="checkbox"     id="data_contact_customfield_values_22_content" name="data[contact][customfield_values][22][content]" value="1">
            <label for="data_contact_customfield_values_22_content">DRH, Direction, PME</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_20_container">
            <input type="checkbox"     id="data_contact_customfield_values_20_content" name="data[contact][customfield_values][20][content]" value="1">
            <label for="data_contact_customfield_values_20_content">BNI</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_19_container">
            <input type="checkbox"     id="data_contact_customfield_values_19_content" name="data[contact][customfield_values][19][content]" value="1">
            <label for="data_contact_customfield_values_19_content">Avocats, juristes</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_31_container">
            <input type="checkbox"     id="data_contact_customfield_values_31_content" name="data[contact][customfield_values][31][content]" value="1">
            <label for="data_contact_customfield_values_31_content">ONG, Ambassades, Coopération, FEDERESO</label>
            <ul class="field_errors"></ul>
        </div>
        <div class="field_container custom_field_container customfield_type_boolean"
             id="custom_field_29_container">
            <input type="checkbox"     id="data_contact_customfield_values_29_content" name="data[contact][customfield_values][29][content]" value="1">
            <label for="data_contact_customfield_values_29_content">Média, journaliste</label>
            <ul class="field_errors"></ul>
        </div>
    </div>
    <div class="col_1">

        <h1 class="headline1" id="headline1_79">Vos coordonnées :</h1>
        <div class="field_container contact_field_container"
             id="contact_field_lastname_container">
            <label for="data_contact_lastname">Prénom</label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_lastname" name="data[contact][lastname]" >
        </div>
        <div class="field_container contact_field_container"
             id="contact_field_firstname_container">
            <label for="data_contact_firstname">Nom</label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_firstname" name="data[contact][firstname]" >
        </div>
        <div class="field_container contact_field_container"
             id="contact_field_company_container">
            <label for="data_contact_company">Société</label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_company" name="data[contact][company]" >
        </div>
        <div class="field_container contact_field_container"
             id="contact_field_address_container">
            <label for="data_contact_address">Adresse</label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_address" name="data[contact][address]" >
        </div>
        <div class="field_container contact_field_container"
             id="contact_field_zip_container">
            <label for="data_contact_zip">NPA</label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_zip" name="data[contact][zip]" >
        </div>
        <div class="field_container contact_field_container"
             id="contact_field_city_container">
            <label for="data_contact_city">Ville</label>
            <ul class="field_errors"></ul>
            <input type="text"     id="data_contact_city" name="data[contact][city]" >
        </div>
        <div class="field_container contact_field_container"
             id="contact_field_country_container">
            <label for="data_contact_country">Pays</label>
            <ul class="field_errors"></ul>
            <select id="data_contact_country" name="data[contact][country]">
                <option value="">Sélectionnez le pays</option>
                <option value="DE">Allemagne</option>
                <option value="FR">France</option>
                <option value="IT">Italie</option>
                <option value="AT">Autriche</option>
                <option value="CH">Suisse</option>
                <option value="US">États-Unis</option>
                <option value="GB">Royaume-Uni</option>
                <option disabled="disabled">-------------------</option>
                <option value="AF">Afghanistan</option>
                <option value="EG">Égypte</option>
                <option value="AX">Îles Åland</option>
                <option value="AL">Albanie</option>
                <option value="DZ">Algérie</option>
                <option value="AS">Samoa américaines</option>
                <option value="VI">Îles Vierges américaines</option>
                <option value="UM">Îles américaines d'outre-mer</option>
                <option value="AD">Andorre</option>
                <option value="AO">Angola</option>
                <option value="AI">Anguilla</option>
                <option value="AQ">Antarctique</option>
                <option value="AG">Antigua et Barbuda</option>
                <option value="GQ">La Guinée équatoriale</option>
                <option value="AR">Argentine</option>
                <option value="AM">Arménie</option>
                <option value="AW">Aruba</option>
                <option value="AC">Ascension</option>
                <option value="AZ">Azerbaïdjan</option>
                <option value="ET">Éthiopie</option>
                <option value="AU">Australien</option>
                <option value="BS">Les Bahamas</option>
                <option value="BH">Bahreïn</option>
                <option value="BD">Bangladesh</option>
                <option value="BB">Barbade</option>
                <option value="BY">Bélarus</option>
                <option value="BE">Belgique</option>
                <option value="BZ">Belize</option>
                <option value="BJ">Bénin</option>
                <option value="BM">Bermudes</option>
                <option value="BT">Bhoutan</option>
                <option value="BO">Bolivie</option>
                <option value="BQ">Bonaire, Sint Eustatius et Saba</option>
                <option value="BA">Bosnie-Herzégovine</option>
                <option value="BW">Botswana</option>
                <option value="BR">Brésil</option>
                <option value="VG">Îles Vierges britanniques</option>
                <option value="IO">Territoire britannique de l'océan Indien</option>
                <option value="BN">Brunei Darussalam</option>
                <option value="BG">Bulgarie</option>
                <option value="BF">Burkina Faso</option>
                <option value="BI">Burundi</option>
                <option value="CV">Cabo Verde</option>
                <option value="EA">Ceuta et Melilla</option>
                <option value="CL">Chili</option>
                <option value="CN">Chine</option>
                <option value="CK">Îles Cook</option>
                <option value="CR">Le Costa Rica</option>
                <option value="CI">Côte d'Ivoire</option>
                <option value="CW">Curaçao</option>
                <option value="DK">Danemark</option>
                <option value="DG">Diego Garcia</option>
                <option value="DM">Dominique</option>
                <option value="DO">République dominicaine</option>
                <option value="DJ">Djibouti</option>
                <option value="EC">Équateur</option>
                <option value="SV">El Salvador</option>
                <option value="ER">Érythrée</option>
                <option value="EE">Estonie</option>
                <option value="SZ">Eswatini</option>
                <option value="FK">Îles Falkland</option>
                <option value="FO">Îles Féroé</option>
                <option value="FJ">Fidji</option>
                <option value="FI">Finlande</option>
                <option value="GF">Guyane française</option>
                <option value="PF">Polynésie française</option>
                <option value="TF">Terres australes et antarctiques françaises</option>
                <option value="GA">Gabon</option>
                <option value="GM">Gambie</option>
                <option value="GE">Géorgie</option>
                <option value="GH">Ghana</option>
                <option value="GI">Gibraltar</option>
                <option value="GD">Grenade</option>
                <option value="GR">Grèce</option>
                <option value="GL">Groenland</option>
                <option value="GP">Guadeloupe</option>
                <option value="GU">Guam</option>
                <option value="GT">Guatemala</option>
                <option value="GG">Guernesey</option>
                <option value="GN">Guinée</option>
                <option value="GW">Guinée-Bissau</option>
                <option value="GY">Guyane</option>
                <option value="HT">Haïti</option>
                <option value="HN">Honduras</option>
                <option value="IN">Inde</option>
                <option value="ID">Indonésie</option>
                <option value="IQ">Irak</option>
                <option value="IR">Iran</option>
                <option value="IE">Irlande</option>
                <option value="IS">Islande</option>
                <option value="IM">Île de Man</option>
                <option value="IL">Israël</option>
                <option value="JM">Jamaïque</option>
                <option value="JP">Japon</option>
                <option value="YE">Yémen</option>
                <option value="JE">Jersey</option>
                <option value="JO">Jordan</option>
                <option value="KY">Îles Caïmans</option>
                <option value="KH">Cambodge</option>
                <option value="CM">Cameroun</option>
                <option value="CA">Canada</option>
                <option value="IC">Îles Canaries</option>
                <option value="KZ">Kazakhstan</option>
                <option value="QA">Qatar</option>
                <option value="KE">Kenya</option>
                <option value="KG">Kirghizistan</option>
                <option value="KI">Kiribati</option>
                <option value="CC">Îles Cocos</option>
                <option value="CO">Colombie</option>
                <option value="KM">Comores</option>
                <option value="CG">Congo-Brazzaville</option>
                <option value="CD">Congo-Kinshasa</option>
                <option value="XK">Kosovo</option>
                <option value="HR">Croatie</option>
                <option value="CU">Cuba</option>
                <option value="KW">Koweït</option>
                <option value="LA">Laos</option>
                <option value="LS">Lesotho</option>
                <option value="LV">Lettonie</option>
                <option value="LB">Liban</option>
                <option value="LR">Liberia</option>
                <option value="LY">Libye</option>
                <option value="LI">Liechtenstein</option>
                <option value="LT">Lituanie</option>
                <option value="LU">Luxemburg</option>
                <option value="MG">Madagascar</option>
                <option value="MW">Malawi</option>
                <option value="MY">Malaisie</option>
                <option value="MV">Maldives</option>
                <option value="ML">Mali</option>
                <option value="MT">Malte</option>
                <option value="MA">Maroc</option>
                <option value="MH">Îles Marshall</option>
                <option value="MQ">Martinique</option>
                <option value="MR">Mauritanie</option>
                <option value="MU">Maurice</option>
                <option value="YT">Mayotte</option>
                <option value="MX">Mexique</option>
                <option value="FM">Micronésie</option>
                <option value="MC">Monaco</option>
                <option value="MN">Mongolie</option>
                <option value="ME">Monténégro</option>
                <option value="MS">Montserrat</option>
                <option value="MZ">Mozambique</option>
                <option value="MM">Myanmar</option>
                <option value="NA">Namibie</option>
                <option value="NR">Nauru</option>
                <option value="NP">Népal</option>
                <option value="NC">Nouvelle-Calédonie</option>
                <option value="NZ">Nouvelle-Zélande</option>
                <option value="NI">Nicaragua</option>
                <option value="NL">Pays-Bas</option>
                <option value="NE">Niger</option>
                <option value="NG">Nigeria</option>
                <option value="NU">Niue</option>
                <option value="KP">Corée du Nord</option>
                <option value="MP">Îles Mariannes du Nord</option>
                <option value="MK">Macédoine du Nord</option>
                <option value="NF">Île Norfolk</option>
                <option value="NO">Norvège</option>
                <option value="OM">Oman</option>
                <option value="PK">Pakistan</option>
                <option value="PS">Territoires autonomes palestiniens</option>
                <option value="PW">Palau</option>
                <option value="PA">Panama</option>
                <option value="PG">Papouasie-Nouvelle-Guinée</option>
                <option value="PY">Paraguay</option>
                <option value="PE">Pérou</option>
                <option value="PH">Philippines</option>
                <option value="PN">Îles Pitcairn</option>
                <option value="PL">Pologne</option>
                <option value="PT">Portugal</option>
                <option value="XA">Pseudo accents</option>
                <option value="XB">Pseudo-Bidi</option>
                <option value="PR">Porto Rico</option>
                <option value="MD">République de Moldavie</option>
                <option value="RE">Réunion</option>
                <option value="RW">Rwanda</option>
                <option value="RO">Roumanie</option>
                <option value="RU">Russie</option>
                <option value="SB">Îles Salomon</option>
                <option value="ZM">Zambie</option>
                <option value="WS">Samoa</option>
                <option value="SM">Saint-Marin</option>
                <option value="ST">São Tomé et Príncipe</option>
                <option value="SA">Arabie Saoudite</option>
                <option value="SE">Suède</option>
                <option value="SN">Sénégal</option>
                <option value="RS">Serbie</option>
                <option value="SC">Seychelles</option>
                <option value="SL">Sierra Leone</option>
                <option value="ZW">Zimbabwe</option>
                <option value="SG">Singapour</option>
                <option value="SX">Sint Maarten</option>
                <option value="SK">Slovaquie</option>
                <option value="SI">Slovénie</option>
                <option value="SO">Somalie</option>
                <option value="HK">Région administrative spéciale de Hong Kong</option>
                <option value="MO">Région administrative spéciale de Macao</option>
                <option value="ES">Espagne</option>
                <option value="SJ">Spitzberg et Jan Mayen</option>
                <option value="LK">Sri Lanka</option>
                <option value="BL">St Barthélemy</option>
                <option value="SH">Sainte-Hélène</option>
                <option value="KN">Saint-Kitts-et-Nevis</option>
                <option value="LC">Sainte-Lucie</option>
                <option value="MF">St. Martin</option>
                <option value="PM">St Pierre et Miquelon</option>
                <option value="VC">Saint-Vincent-et-les-Grenadines</option>
                <option value="ZA">Afrique du Sud</option>
                <option value="SD">Soudan</option>
                <option value="GS">Géorgie du Sud et les îles Sandwich du Sud</option>
                <option value="KR">Corée du Sud</option>
                <option value="SS">Sud-Soudan</option>
                <option value="SR">Suriname</option>
                <option value="SY">Syrie</option>
                <option value="TJ">Tadjikistan</option>
                <option value="TW">Taiwan</option>
                <option value="TZ">Tanzanie</option>
                <option value="TH">Thaïlande</option>
                <option value="TL">Timor-Leste</option>
                <option value="TG">Togo</option>
                <option value="TK">Tokelau</option>
                <option value="TO">Tonga</option>
                <option value="TT">Trinité-et-Tobago</option>
                <option value="TA">Tristan da Cunha</option>
                <option value="TD">Chad</option>
                <option value="CZ">République tchèque</option>
                <option value="TN">Tunisie</option>
                <option value="TR">Turquie</option>
                <option value="TM">Turkménistan</option>
                <option value="TC">Îles Turks et Caicos</option>
                <option value="TV">Tuvalu</option>
                <option value="UG">Ouganda</option>
                <option value="UA">Ukraine</option>
                <option value="HU">Hongrie</option>
                <option value="UY">Uruguay</option>
                <option value="UZ">Ouzbékistan</option>
                <option value="VU">Vanuatu</option>
                <option value="VA">Cité du Vatican</option>
                <option value="VE">Venezuela</option>
                <option value="AE">Émirats arabes unis</option>
                <option value="VN">Vietnam</option>
                <option value="WF">Wallis et Futuna</option>
                <option value="CX">Île Christmas</option>
                <option value="EH">Sahara occidental</option>
                <option value="CF">République centrafricaine</option>
                <option value="CY">Chypre</option>
            </select>

        </div>

        <div class="field_container contact_field_container"
             id="contact_field_standard_language_container">
            <label for="data_contact_standard_language">Langue principale</label>
            <ul class="field_errors"></ul>
            <select id="data_contact_standard_language" name="data[contact][standard_language]">
                <option selected="selected" value="fr">Français</option>
                <option disabled="disabled">-------------------</option>
                <option value="ab">Abkhazie</option>
                <option value="ace">Aceh</option>
                <option value="ach">Acholi</option>
                <option value="ada">Adangme</option>
                <option value="ady">Adygean</option>
                <option value="aa">Afar</option>
                <option value="afh">Afrihili</option>
                <option value="af">Afrikaner</option>
                <option value="agq">Aghem</option>
                <option value="egy">Égypte</option>
                <option value="arz">Arabe égyptien</option>
                <option value="ain">Ainu</option>
                <option value="ak">Akan</option>
                <option value="akk">Akkadien</option>
                <option value="bss">Akoose</option>
                <option value="akz">Alabama</option>
                <option value="sq">Albanais</option>
                <option value="de">Allemand</option>
                <option value="ale">Aléoute</option>
                <option value="arq">Algérien Arabe</option>
                <option value="nwc">Ancien Newari</option>
                <option value="grc">Grec ancien</option>
                <option value="goh">Vieux haut allemand</option>
                <option value="sga">Vieil irlandais</option>
                <option value="non">Vieux Norrois</option>
                <option value="peo">Vieux Persan</option>
                <option value="prg">Vieux Prussien</option>
                <option value="pro">Vieux Provençal</option>
                <option value="syc">Vieux syriaque</option>
                <option value="en_US">Anglais américain</option>
                <option value="ase">Langue des signes américaine</option>
                <option value="am">Amharique</option>
                <option value="anp">Angika</option>
                <option value="njo">Ao-Naga</option>
                <option value="ar">Arabe</option>
                <option value="ars">Arabe (Najd)</option>
                <option value="an">Aragonais</option>
                <option value="arc">Araméen</option>
                <option value="aro">Araona</option>
                <option value="arp">Arapaho</option>
                <option value="arw">Arawak</option>
                <option value="hy">Arménien</option>
                <option value="rup">Aromunien</option>
                <option value="az">Azerbaïdjanais</option>
                <option value="as">Assamese</option>
                <option value="ast">Asturien</option>
                <option value="asa">Asu</option>
                <option value="cch">Atsam</option>
                <option value="en_AU">Anglais australien</option>
                <option value="ae">Avestic</option>
                <option value="awa">Awadhi</option>
                <option value="av">Avaric</option>
                <option value="ay">Aymara</option>
                <option value="bqi">Bakhtiari</option>
                <option value="bfq">Badaga</option>
                <option value="ksf">Bafia</option>
                <option value="bfd">Bafut</option>
                <option value="bar">Bairisch</option>
                <option value="ban">Balinais</option>
                <option value="bm">Bambara</option>
                <option value="bax">Bamun</option>
                <option value="bjn">Banjarese</option>
                <option value="bas">Basaa</option>
                <option value="ba">Bashkir</option>
                <option value="eu">Basque</option>
                <option value="bbc">Batak Toba</option>
                <option value="bej">Bedauye</option>
                <option value="bal">Baluchi</option>
                <option value="bem">Bemba</option>
                <option value="bez">Bena</option>
                <option value="bn">Bengali</option>
                <option value="mrj">Bergmari</option>
                <option value="bew">Betawi</option>
                <option value="bho">Bhodschpuri</option>
                <option value="bik">Bikol</option>
                <option value="bin">Bini</option>
                <option value="my">Birmane</option>
                <option value="bpy">Bishnupriya</option>
                <option value="bi">Bislama</option>
                <option value="bla">Blackfoot</option>
                <option value="byn">Blin</option>
                <option value="zbl">Blissymbole</option>
                <option value="brx">Bodo</option>
                <option value="bs">Bosniaque</option>
                <option value="brh">Brahui</option>
                <option value="bra">Braj-Bhakha</option>
                <option value="pt_BR">Portugais du Brésil</option>
                <option value="br">Breton</option>
                <option value="en_GB">Anglais britannique</option>
                <option value="bug">Buginese</option>
                <option value="bg">Bulgare</option>
                <option value="bum">Bulu</option>
                <option value="bua">Bouriate</option>
                <option value="cad">Caddo</option>
                <option value="frc">Cajun</option>
                <option value="en_CA">Anglais canadien</option>
                <option value="fr_CA">Français canadien</option>
                <option value="cps">Capiznon</option>
                <option value="cay">Cayuga</option>
                <option value="ceb">Cebuano</option>
                <option value="ccp">Chakma</option>
                <option value="ch">Chamorro</option>
                <option value="chr">Cherokee</option>
                <option value="chy">Cheyenne</option>
                <option value="chb">Chibcha</option>
                <option value="cic">Chickasaw</option>
                <option value="qug">Chimborazo Highland Quechua</option>
                <option value="zh">Chinois</option>
                <option value="zh_Hant">Chinois (traditionnel)</option>
                <option value="zh_Hans">Chinois (simplifié)</option>
                <option value="chn">Chinook</option>
                <option value="chp">Chipewyan</option>
                <option value="cho">Choctaw</option>
                <option value="chk">Chuukese</option>
                <option value="cr">Cri</option>
                <option value="dak">Dakota</option>
                <option value="da">Danois</option>
                <option value="dar">Dargin</option>
                <option value="fa_AF">Dari</option>
                <option value="dzg">Dazaga</option>
                <option value="del">Delaware</option>
                <option value="dv">Dhivehi</option>
                <option value="din">Dinka</option>
                <option value="dyo">Diola</option>
                <option value="doi">Dogri</option>
                <option value="dgr">Dogrib</option>
                <option value="dua">Duala</option>
                <option value="dyu">Dyula</option>
                <option value="dz">Dzongkha</option>
                <option value="efi">Efik</option>
                <option value="eka">Ekajuk</option>
                <option value="elx">Elamian</option>
                <option value="ebu">Embu</option>
                <option value="egl">Emilien</option>
                <option value="en">Anglais</option>
                <option value="myv">Ersja-Mordovie</option>
                <option value="eo">Espéranto</option>
                <option value="et">Estonien</option>
                <option value="pt_PT">Portugais européen</option>
                <option value="es_ES">Espagnol européen</option>
                <option value="ee">Ewe</option>
                <option value="ewo">Ewondo</option>
                <option value="ext">Extremadurian</option>
                <option value="fat">Fanti</option>
                <option value="gur">Farefare</option>
                <option value="fo">Féroïques</option>
                <option value="fj">Fidji</option>
                <option value="hif">Fidji-Hindi</option>
                <option value="fil">Philippine</option>
                <option value="fi">Finlandais</option>
                <option value="nl_BE">Flamand</option>
                <option value="fon">Fon</option>
                <option value="frp">Franco-Provençal</option>
                <option value="fur">Frioulan</option>
                <option value="ff">Ful</option>
                <option value="gaa">Ga</option>
                <option value="gbz">Gabri</option>
                <option value="gag">Gagauz</option>
                <option value="gl">Galicien</option>
                <option value="gan">Gan</option>
                <option value="lg">Ganda</option>
                <option value="gay">Gayo</option>
                <option value="gba">Gbaya</option>
                <option value="gez">Geez</option>
                <option value="aln">Gegisch</option>
                <option value="ka">Géorgien</option>
                <option value="bbj">Ghomala</option>
                <option value="glk">Gilaki</option>
                <option value="gom">Goa-Konkani</option>
                <option value="gon">Gondi</option>
                <option value="got">Gothique</option>
                <option value="grb">Grebo</option>
                <option value="el">Grec</option>
                <option value="kl">Groenlandais</option>
                <option value="gn">Guaraní</option>
                <option value="gu">Gujarati</option>
                <option value="guz">Gusii</option>
                <option value="hai">Haida</option>
                <option value="ht">Créole haïtien</option>
                <option value="hak">Hakka</option>
                <option value="ha">Haussa</option>
                <option value="haw">Hawaïen</option>
                <option value="he">Hébreu</option>
                <option value="hz">Herero</option>
                <option value="hit">Hittite</option>
                <option value="hil">Hiligaynon</option>
                <option value="hi">Hindi</option>
                <option value="ho">Hiri-Motu</option>
                <option value="hup">Hupa</option>
                <option value="iba">Iban</option>
                <option value="ibb">Ibibio</option>
                <option value="io">Ido</option>
                <option value="ig">Igbo</option>
                <option value="ilo">Ilokano</option>
                <option value="smn">Inari-Samish</option>
                <option value="id">Indonésien</option>
                <option value="inh">Ingush</option>
                <option value="ia">Interlingua</option>
                <option value="ie">Interlingue</option>
                <option value="iu">Inuktitut</option>
                <option value="ik">Inupiak</option>
                <option value="ga">Irlandais</option>
                <option value="izh">Ischoric</option>
                <option value="is">Islandais</option>
                <option value="it">Italien</option>
                <option value="sah">Yakoutie</option>
                <option value="jam">Créole jamaïcain</option>
                <option value="ja">Japonais</option>
                <option value="jv">Javanais</option>
                <option value="yi">Yiddish</option>
                <option value="kaj">Jju</option>
                <option value="jrb">Judéo-Arabe</option>
                <option value="jpr">Juifs et Perses</option>
                <option value="jut">Jutish</option>
                <option value="quc">K’iche’</option>
                <option value="kbd">Kabardian</option>
                <option value="kea">Kabuverdianu</option>
                <option value="kab">Kabyle</option>
                <option value="kac">Kachin</option>
                <option value="kgp">Kaingang</option>
                <option value="kkj">Kako</option>
                <option value="kln">Kalenjin</option>
                <option value="xal">Kalmyk</option>
                <option value="kam">Kamba</option>
                <option value="kbl">Kanembu</option>
                <option value="kn">Kannada</option>
                <option value="yue">Cantonais</option>
                <option value="kr">Kanuri</option>
                <option value="kaa">Karakalpakian</option>
                <option value="krc">Karachay-Balkarie</option>
                <option value="krl">Carélie</option>
                <option value="car">Caraïbes</option>
                <option value="kk">Kazakh</option>
                <option value="ks">Cachemire</option>
                <option value="csb">Kashubian</option>
                <option value="ca">Catalan</option>
                <option value="kaw">Kawi</option>
                <option value="zxx">Aucun contenu linguistique</option>
                <option value="ken">Kenyang</option>
                <option value="kha">Khasi</option>
                <option value="km">Khmer</option>
                <option value="mag">Khotta</option>
                <option value="khw">Khowar</option>
                <option value="ki">Kikuyu</option>
                <option value="kmb">Kimbundu</option>
                <option value="krj">Kinaray-a</option>
                <option value="rw">Kinyarwanda</option>
                <option value="cu">Église slave</option>
                <option value="ky">Kirghizistan</option>
                <option value="gil">Kiribati</option>
                <option value="kiu">Kirmanjki</option>
                <option value="lzh">Chinois classique</option>
                <option value="tlh">Klingon</option>
                <option value="ksh">Kölsch</option>
                <option value="bkm">Com</option>
                <option value="kv">Komi</option>
                <option value="koi">Komi-Permjakian</option>
                <option value="swb">Comores</option>
                <option value="sw_CD">Congo Swahili</option>
                <option value="kg">Congolais</option>
                <option value="kok">Konkani</option>
                <option value="cop">Copte</option>
                <option value="ko">Coréen</option>
                <option value="kw">Cornouailles</option>
                <option value="kfo">Koro</option>
                <option value="co">Corse</option>
                <option value="kos">Kosraean</option>
                <option value="avk">Kotava</option>
                <option value="khq">Koyra Chiini</option>
                <option value="ses">Koyra Senni</option>
                <option value="kpe">Kpelle</option>
                <option value="lou">Créole (Louisiane)</option>
                <option value="crh">Tatar de Crimée</option>
                <option value="kri">Krio</option>
                <option value="hr">Croate</option>
                <option value="kum">Cumükish</option>
                <option value="ku">Kurde</option>
                <option value="gwi">Kutchin</option>
                <option value="kut">Kutenai</option>
                <option value="kj">Kwanyama</option>
                <option value="nmg">Kwasio</option>
                <option value="lad">Ladino</option>
                <option value="lah">Lahnda</option>
                <option value="lkt">Lakota</option>
                <option value="lam">Lamba</option>
                <option value="lag">Langi</option>
                <option value="lo">Lao</option>
                <option value="lzz">Lasisch</option>
                <option value="la">Latin</option>
                <option value="es_419">Espagnol d'Amérique latine</option>
                <option value="lez">Lesgien</option>
                <option value="ltg">Latgallique</option>
                <option value="lv">Letton</option>
                <option value="lij">Ligurie</option>
                <option value="li">Limbourg</option>
                <option value="ln">Lingala</option>
                <option value="lfn">Lingua Franca Nova</option>
                <option value="lt">Lituanien</option>
                <option value="liv">Livonien</option>
                <option value="jbo">Lojban</option>
                <option value="lmo">Lombard</option>
                <option value="loz">Lozi</option>
                <option value="lu">Luba-Katanga</option>
                <option value="lua">Luba-Lulua</option>
                <option value="luy">Luhya</option>
                <option value="lui">Luiseno</option>
                <option value="smj">Lule-Samisch</option>
                <option value="lun">Lunda</option>
                <option value="luo">Luo</option>
                <option value="lus">Lushai</option>
                <option value="lb">Luxembourgeois</option>
                <option value="mde">Maba</option>
                <option value="jmc">Machame</option>
                <option value="mg">Malgache</option>
                <option value="mad">Madurese</option>
                <option value="maf">Mafa</option>
                <option value="vmf">Mainfränkisch</option>
                <option value="mai">Maithili</option>
                <option value="mak">Macassarese</option>
                <option value="mgh">Makhuwa-Meetto</option>
                <option value="kde">Makonde</option>
                <option value="ms">Malais</option>
                <option value="ml">Malayalam</option>
                <option value="man">Malinke</option>
                <option value="mt">Maltais</option>
                <option value="mdr">Mandarine</option>
                <option value="mnc">Mandchourie</option>
                <option value="gv">Manx</option>
                <option value="mi">Maori</option>
                <option value="arn">Mapudungun</option>
                <option value="mr">Marathi</option>
                <option value="chm">Mari</option>
                <option value="ary">Arabe marocain</option>
                <option value="mh">Marshallese</option>
                <option value="mwr">Marwari</option>
                <option value="mzn">Masanderan</option>
                <option value="mas">Massai</option>
                <option value="mk">Macédoine</option>
                <option value="fit">Meänkieli</option>
                <option value="byv">Medumba</option>
                <option value="mul">Multilingue</option>
                <option value="mni">Meithei</option>
                <option value="men">Mende</option>
                <option value="mwv">Mentawai</option>
                <option value="mer">Meru</option>
                <option value="mgo">Meta’</option>
                <option value="es_MX">Espagnol mexicain</option>
                <option value="hmn">Miao</option>
                <option value="mic">Micmac</option>
                <option value="nan">Min Nan</option>
                <option value="min">Minangkabau</option>
                <option value="xmf">Mingrelian</option>
                <option value="mwl">Mirandese</option>
                <option value="enm">Anglais moyen</option>
                <option value="frm">Moyen français</option>
                <option value="gmh">Moyen haut allemand</option>
                <option value="mga">Moyen irlandais</option>
                <option value="dum">Moyen Néerlandais</option>
                <option value="pal">Moyen Persan</option>
                <option value="ar_001">Haut arabe moderne</option>
                <option value="moh">Mohawk</option>
                <option value="mdf">Mokshan</option>
                <option value="ro_MD">Moldavie</option>
                <option value="lol">Mongo</option>
                <option value="mn">Mongolie</option>
                <option value="gor">Mongondou</option>
                <option value="sr_ME">Monténégrin</option>
                <option value="mfe">Morisyen</option>
                <option value="mos">Mossi</option>
                <option value="mua">Mundang</option>
            </select>
        </div>

        <div class="field_container contact_field_container"
             id="contact_field_phone_container">
            <label for="data_contact_phone">No. de tél.</label>
            <ul class="field_errors"></ul>
            <div id="data_contact_phone"><div class="phonenumber_widget">
                    <select id="data_contact_phone_country_code" name="data[contact][phone][country_code]">
                        <option value="">Choisir</option>
                        <option value="41">+41</option>
                        <option value="1">+1</option>
                        <option value="7">+7</option>
                        <option value="20">+20</option>
                        <option value="27">+27</option>
                        <option value="30">+30</option>
                        <option value="31">+31</option>
                        <option value="32">+32</option>
                        <option value="33">+33</option>
                        <option value="34">+34</option>
                        <option value="36">+36</option>
                        <option value="39">+39</option>
                        <option value="40">+40</option>
                        <option value="43">+43</option>
                        <option value="44">+44</option>
                        <option value="45">+45</option>
                        <option value="46">+46</option>
                        <option value="47">+47</option>
                        <option value="48">+48</option>
                        <option value="49">+49</option>
                        <option value="51">+51</option>
                        <option value="52">+52</option>
                        <option value="53">+53</option>
                        <option value="54">+54</option>
                        <option value="55">+55</option>
                        <option value="56">+56</option>
                        <option value="57">+57</option>
                        <option value="58">+58</option>
                        <option value="60">+60</option>
                        <option value="61">+61</option>
                        <option value="62">+62</option>
                        <option value="63">+63</option>
                        <option value="64">+64</option>
                        <option value="65">+65</option>
                        <option value="66">+66</option>
                        <option value="81">+81</option>
                        <option value="82">+82</option>
                        <option value="84">+84</option>
                        <option value="86">+86</option>
                        <option value="90">+90</option>
                        <option value="91">+91</option>
                        <option value="92">+92</option>
                        <option value="93">+93</option>
                        <option value="94">+94</option>
                        <option value="95">+95</option>
                        <option value="98">+98</option>
                        <option value="211">+211</option>
                        <option value="212">+212</option>
                        <option value="213">+213</option>
                        <option value="216">+216</option>
                        <option value="218">+218</option>
                        <option value="220">+220</option>
                        <option value="221">+221</option>
                        <option value="222">+222</option>
                        <option value="223">+223</option>
                        <option value="224">+224</option>
                        <option value="225">+225</option>
                        <option value="226">+226</option>
                        <option value="227">+227</option>
                        <option value="228">+228</option>
                        <option value="229">+229</option>
                        <option value="230">+230</option>
                        <option value="231">+231</option>
                        <option value="232">+232</option>
                        <option value="233">+233</option>
                        <option value="234">+234</option>
                        <option value="235">+235</option>
                        <option value="236">+236</option>
                        <option value="237">+237</option>
                        <option value="238">+238</option>
                        <option value="239">+239</option>
                        <option value="240">+240</option>
                        <option value="241">+241</option>
                        <option value="242">+242</option>
                        <option value="243">+243</option>
                        <option value="244">+244</option>
                        <option value="245">+245</option>
                        <option value="246">+246</option>
                        <option value="247">+247</option>
                        <option value="248">+248</option>
                        <option value="249">+249</option>
                        <option value="250">+250</option>
                        <option value="251">+251</option>
                        <option value="252">+252</option>
                        <option value="253">+253</option>
                        <option value="254">+254</option>
                        <option value="255">+255</option>
                        <option value="256">+256</option>
                        <option value="257">+257</option>
                        <option value="258">+258</option>
                        <option value="260">+260</option>
                        <option value="261">+261</option>
                        <option value="262">+262</option>
                        <option value="263">+263</option>
                        <option value="264">+264</option>
                        <option value="265">+265</option>
                        <option value="266">+266</option>
                        <option value="267">+267</option>
                        <option value="268">+268</option>
                        <option value="269">+269</option>
                        <option value="290">+290</option>
                        <option value="291">+291</option>
                        <option value="297">+297</option>
                        <option value="298">+298</option>
                        <option value="299">+299</option>
                        <option value="350">+350</option>
                        <option value="351">+351</option>
                        <option value="352">+352</option>
                        <option value="353">+353</option>
                        <option value="354">+354</option>
                        <option value="355">+355</option>
                        <option value="356">+356</option>
                        <option value="357">+357</option>
                        <option value="358">+358</option>
                        <option value="359">+359</option>
                        <option value="370">+370</option>
                        <option value="371">+371</option>
                        <option value="372">+372</option>
                        <option value="373">+373</option>
                        <option value="374">+374</option>
                        <option value="375">+375</option>
                        <option value="376">+376</option>
                        <option value="377">+377</option>
                        <option value="378">+378</option>
                        <option value="380">+380</option>
                        <option value="381">+381</option>
                        <option value="382">+382</option>
                        <option value="383">+383</option>
                        <option value="385">+385</option>
                        <option value="386">+386</option>
                        <option value="387">+387</option>
                        <option value="389">+389</option>
                        <option value="420">+420</option>
                        <option value="421">+421</option>
                        <option value="423">+423</option>
                        <option value="500">+500</option>
                        <option value="501">+501</option>
                        <option value="502">+502</option>
                        <option value="503">+503</option>
                        <option value="504">+504</option>
                        <option value="505">+505</option>
                        <option value="506">+506</option>
                        <option value="507">+507</option>
                        <option value="508">+508</option>
                        <option value="509">+509</option>
                        <option value="590">+590</option>
                        <option value="591">+591</option>
                        <option value="592">+592</option>
                        <option value="593">+593</option>
                        <option value="594">+594</option>
                        <option value="595">+595</option>
                        <option value="596">+596</option>
                        <option value="597">+597</option>
                        <option value="598">+598</option>
                        <option value="599">+599</option>
                        <option value="670">+670</option>
                        <option value="672">+672</option>
                        <option value="673">+673</option>
                        <option value="674">+674</option>
                        <option value="675">+675</option>
                        <option value="676">+676</option>
                        <option value="677">+677</option>
                        <option value="678">+678</option>
                        <option value="679">+679</option>
                        <option value="680">+680</option>
                        <option value="681">+681</option>
                        <option value="682">+682</option>
                        <option value="683">+683</option>
                        <option value="685">+685</option>
                        <option value="686">+686</option>
                        <option value="687">+687</option>
                        <option value="688">+688</option>
                        <option value="689">+689</option>
                        <option value="690">+690</option>
                        <option value="691">+691</option>
                        <option value="692">+692</option>
                        <option value="800">+800</option>
                        <option value="808">+808</option>
                        <option value="850">+850</option>
                        <option value="852">+852</option>
                        <option value="853">+853</option>
                        <option value="855">+855</option>
                        <option value="856">+856</option>
                        <option value="870">+870</option>
                        <option value="878">+878</option>
                        <option value="880">+880</option>
                        <option value="881">+881</option>
                        <option value="882">+882</option>
                        <option value="883">+883</option>
                        <option value="886">+886</option>
                        <option value="888">+888</option>
                        <option value="960">+960</option>
                        <option value="961">+961</option>
                        <option value="962">+962</option>
                        <option value="963">+963</option>
                        <option value="964">+964</option>
                        <option value="965">+965</option>
                        <option value="966">+966</option>
                        <option value="967">+967</option>
                        <option value="968">+968</option>
                        <option value="970">+970</option>
                        <option value="971">+971</option>
                        <option value="972">+972</option>
                        <option value="973">+973</option>
                        <option value="974">+974</option>
                        <option value="975">+975</option>
                        <option value="976">+976</option>
                        <option value="977">+977</option>
                        <option value="979">+979</option>
                        <option value="992">+992</option>
                        <option value="993">+993</option>
                        <option value="994">+994</option>
                        <option value="995">+995</option>
                        <option value="996">+996</option>
                        <option value="998">+998</option>
                    </select>
                    <input type="text"     id="data_contact_phone_number" name="data[contact][phone][number]" ></div></div>
        </div>
        <div class="submit_container">
            <input class="submit_button" id="submit_button_65" type="submit" value="Senden">
        </div>
    </div>

    <input type="hidden"     id="data_form_version" name="data[form_version]" value="5_0" >
    <input type="hidden"     id="data_referrer" name="data[referrer]" >
    <input type="hidden" id="data_form_validate_data" name="form_validate_data"
           value='{"data_contact_standard_language":{"constrains":[]},"data_contact_email":{"constrains":{"required":true}},"data_contact_company":{"constrains":[]},"data_contact_firstname":{"constrains":[]},"data_contact_lastname":{"constrains":[]},"data_contact_address":{"constrains":[]},"data_contact_zip":{"constrains":[]},"data_contact_city":{"constrains":[]},"data_contact_country":{"constrains":[]},"data_contact_phone":{"constrains":[],"transformer":"phonenumber"},"data_contact_customfield_values_17_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_18_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_19_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_20_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_22_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_23_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_25_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_26_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_28_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_29_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_30_content":{"constrains":[],"transformer":"checkbox"},"data_contact_customfield_values_31_content":{"constrains":[],"transformer":"checkbox"}}'>
    <input type="hidden"     id="data_form_id" name="data[form_id]" value="1" >
    <input type="hidden"     id="data_form_language" name="data[form_language]" value="de" >

    <script type="text/javascript">
        var inputReferrer = document.getElementById('data_referrer');
        if (inputReferrer) {inputReferrer.value = window.location.href;}
    </script>
</form>